# Generated by Django 4.2 on 2024-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ru',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_uz',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
